pipeline {
    agent any
    
    tools{
        jdk 'jdk11'
        maven 'maven3'
    }
    environment {
        SCANNER_HOME= tool 'sonar-scanner'
    }

    stages {
        stage('git-checkout') {
            steps {
                git branch: 'main', changelog: false, poll: false, url: 'https://github.com/Chiran21/newcicd.git'
            }
        }
        
        stage('Code-Compile') {
            steps {
               sh "mvn clean compile"
            }
        }
	
        stage('SONARQUBE ANALYSIS') {
            steps {
               withSonarQubeEnv('sonar-scanner') {
                sh ''' $SCANNER_HOME/bin/sonar-scanner -Dsonar.projectName=newcicd \
                    -Dsonar.java.binaries=. \
                    -Dsonar.projectKey=newcicd'''
               }
            }
        }

        stage('Trivy Scan') {
            steps {
               sh"trivy fs --security-checks vuln, config /var/lib/jenkins/workspace/newcicd"
            }
        }

        stage('Code-Build') {
            steps {
               sh "mvn clean install"
            }
        }
       
        stage('DOCKER BUILD') {
            steps {
               script {

                    sh "docker build -t newcicd ."
               }
               
            }
        }

        stage('DOCKER PUSH') {
            steps {
               script {

                    sh "docker tag newcicd chiran69/newcicd:$BUILD_ID"
                    sh "docker push chiran69/newcicd:$BUILD_ID"
               }
               
            }
        }
        stage('Deploy to K8s') {
            steps {
               
            }
        }
    }
}
